language: go
sudo: false
go:
- 1.7
- tip
before_install:
- go get github.com/hashicorp/terraform
- go get github.com/hashicorp/go-cleanhttp
install:
- make install
script:
- make test
before_deploy:
- make release
deploy:
  provider: releases
  api_key:
    secure: MZOznxDJeaIT3IQYDZHoH7oazeuM8ekgZzvnUTq0gMHZc1gwB9uEYjvCwSVo0OlUKFPymarhv/65GolggV1+fZzig5HPOpJltTFj3w9RBXZZzZiNZ3X+eexyW+so07BtV1S+jytA/Dd8MpnT9EmCYTzpg6Gp/NosyQJ9FbS7hm8UQcH7PLiBWAeoL1Wb/aLZQZUQRBiYr8PmZ6lzVTY+w8h5KISi7TrL6EzbwXj3j3muCGm/9ZqX/6CAxmAydU0ozCjl4QksRqn2MDWgUSYgga2GKBqsTpU4hX05QCEXD/G2BcGmoaOFP29na+zhXlCZ9j7DrOCMisEWH/DiWwqWaNlqUgO81pGbQDayvpZAMGRrYsaSQTz7oEbuU88NeDFriy44WFGE+eE73ykPFQl6JNnptE3mF6dRVPb6GZhG0nzM+UKfNw4hhcWo45hmrfqLS8MJNci9O3HbMy+2Ka45u64RlX2AUnmNexdPFDmZSjARLrnFT4VUuTEeb3CRS8TmNaWEM1o2yWYgtCkM9qnhiAxlrcDt1Y/bqhgbhzoheslHmi+n9TlFeH1xHP9sTEOwji5ljyPv2iN0/YdInkz+lF/4gEQSZ6hvLGGp+v3FUV66PU8dCusw9ysJhlJ40pvobz7MNdsiscDBx0zqiYUAdSR7XSgUQV7aOJH6dmnqwQA=
  file:
  - release/terraform-provider-alks-darwin-386
  - release/terraform-provider-alks-darwin-amd64
  - release/terraform-provider-alks-freebsd-386
  - release/terraform-provider-alks-freebsd-amd64
  - release/terraform-provider-alks-linux-386
  - release/terraform-provider-alks-linux-amd64
  - release/terraform-provider-alks-solaris-amd64
  - release/terraform-provider-alks-windows-386
  - release/terraform-provider-alks-windows-amd64
  skip_cleanup: true
  on:
    repo: Cox-Automotive/terraform-provider-alks
    tags: true
    all_branches: false
notifications:
  email: false
  slack:
    secure: FbWAAe1dJvSEC5dhIozsPG94it3WusO149EMdp+tq2pP4VqAek1l6yKtfzuns5NJhdQHyYj4ERMd74l5u98vgZWHHHjUMr7d/4eFlAY3OpfyGNjFInqzmsAkccV0z8wB4Os15kOUM4hNYRJPbOm/17xvGi+eWQVj8XxVsowSe7goSazibNyjd4RQCaM0E4u6GDJlAqgKqw4sP07AsXEiWSI/A1KhifoNOXhK7mFIFvEJrhvahlUuHoQ0NrtHSx1IKo+efxip3usmREEmnNERTTUKRhmo0T7drV0j/IWvb1UNkq9MRsNOOyAgAC7hv7D3GXBFTXylzxB68OnU+f79XDGdivaq3qRAu4WukIrB78ygKdeBD/DeFZtB7DoYtGjSKkArjbRCNTSq1Jux68+mxxNmZ5L5vGRO2P7mciuFRfzx3VT6XsAfEpmEj1J834nkOWZa10Bdxfd0AIN9Ay3w7d6i60yp6F+jzCN7IxQSj9xHu3VV+rtgYdh8ablsmN1zGU4EqvXZtz5qUpw66ZCT8Z9xQq5R2aXtzd9v/xtdopMT6madwBrDPyqnwMluWLHO+y7XXJLzP0dd+6eEozs4uldjUgLbI8w+YCaePe1HXQCxxyNAIvOK5OA8uO32VUgK2VgTilZYquQUP1F9ncdNOknwwVMt1SaeBrr7a+k0fbk=
matrix:
  fast_finish: true
  allow_failures:
  - go: tip
env:
  ALKS_URL:
    secure: AzWWZsI5G9wDKMHcn7LNsB2KZMNMHuiTdzU1hjMgHKY2PEs5HK+3xPGEWYQv3Nzdrk0kaNy7GEZ5UYhrkAwpWeynBg6yu7tBPETzgExJ1B0Jwm71765aCIWK5yCn9KmXnh10TJJPNhY0M3qD/EzzONL70QcvLSTnOAvBKBz9Etb3GX+S0lHTCXohk71ycKhucX+dKHNwgpMJob4bhfZr6p9N/UUdpLhAyK02XjNCIF9vUJf/fF12eSQ0eLO4Xh2IdIwRSkw2ZcptkJUtaE0qU++B6ehzQQrSXBUMqlCHiasiVruHOD0gIED2oV2k4WtRl8zl5LnVBmBqGtUGcRUhVvSR7p5TrV2ZvCIxnr24EDaYAU+260AVheA1mmt7AwCtC7fzhipdreWDZixE/12xaQJKbJiDUNvEdgm24ByqrNvPhl5Rk9U16jy27/zDD1FUrgtI3pGdXtZsnaN2RcMuRQiKoW1o7w/YeKCfGbNyPto6fZAA2klMkOhGsM8ctOrOPbVvdkI1hQgquS7roQN4aDht56ZDwp8VoYdlPpdOBvijjrDRcjV+o3PpnRte6abb4Z92j7EDJMSv+jjSVTG6VWVQinE7pfOslmd0yX0atv+FtKuf7IGehYyPHeQQICIrPRixBl7UBReLPzHyVBwLmcDvltiUUGRj8O16rnDp410=
  ALKS_ACCOUNT:
    secure: PddZ8k0NxqvHsXWMtu58mG4N5hnw4kle5tnmLlQLw0/tU90p4UZiSlVREe2cTaWvMtgSNsWPEVT6D2Jl8r3z2PrCRXLehUMdg+YbmSPZaHL74fxkUtyqIh2XQF9wrwIvg1tWdsWXOsdu4G5EI3hHPgCB/MzLq+lEkqeQrTlAxR9c/viZXnjYMpTma1xF6xRf2/+P59PtpcBdY3Q0nbtxv/qWT5+ADvxlt76NKQH/wV3IzkbNVmD5OO6lvOxxTevvFT7h5NbAoMXvUq41CUp0b51biVkUpxkSQ0Zx9yPE8d1p4558jj3hVoFre0ntTgx2BoznsAz4FyW/Xa/tY63SBOi2D/0qseZc3xYO3OlHsv/PQhs+xDJKfPxpaMSq2Act8RRBy4kUgf/TS+GpPvUbh6xludbmAHSedrXETXOHDHhuOXwpvItP/EDLHQiNU+G+dy00cqLOy11YJBd92FA3gyMR3+h94Po9Tbf3O5Xz0YezP3CO9vAwQnmZwuzsk+cELdTXm3umfSTFhn0ijCYeujCeOjvH5E+PFvuizdHUyklFQULhRSoxBJKMS8hZPqfObGqr1TAyQ5NqmR+SWvVvy6fNt8LJolYWl2KPMeD2W2HRQJl6CMwpMeueR2DLlCJTPwhrxaMU+VJNkfQrtOwcdtYbkIoV2rVc+5Clm3esz1E=
  ALKS_ROLE:
    secure: QDrghXMy+6f/Eymsw8OTPdm52mk8bOgGM7Pd42mHce1akghWhZef1orpiJGsBvgtGrENMI8rSQArkTli5bNdcPbEAMYKn7M/L5YstlTe6/xdKGPcUPbzpAouUwDMR9L3MIQbIskKBMyYwj0n9JYDmbhXqc5eYokosl5LyP7MzXTDeGnFCGxnoASVQOLtcqHdt6wxxy8wRDiX/Y0Rb2gXJfPkr6/SxUm3xXD4dTII2PKfg93n6CjZ7xOs8bDy5K7nfO6s2rwfuZGtt/k32J+3UjnbEW9Isj5ZKIcZwEVmVZ1fyOYu/1Z9gDiFhf1mORcuELyJbZgpVrg92Tl4LK6KzWxBxkaw7jE4IUCQKKQCq+kA4wfvnYGMEkrKLXReFewIA6Dc1haEDLMxRtSv8/uoCJra93QgZZgXUeFDaP1snr6GsXtECDtKRa5nAMgoJZDtAXl3lPrldTdtnk6wdIQOeRl/JidK6mQi27hy8V2UrIAYbG9gMgzeE2suLxS/2ZJ2NAY/8L7qXikO07dmBJqif/QjxVa2+eCZwcXB5I4Kj+cb4wYuRD8gilIF6Pc2ByPuOpt6Trc5VtInc6NUIbg+gltdROaq64d61KQSKL3Y1nSMra5o3khnO2FbYs7Aols9f7X2garc8olGTlz+Q6lNfC3R5WwmWQgSoGXDzzMLX5k=
  ALKS_USERNAME:
    secure: bGDMToQWEgQm9x6TFEKatRYuMcxfXH5c8owcuzYLL2QEpgzWkHDea4bvvq1EE4aarZO8HlkrulvB4ZNFirofl0NGasMcLI8K5EsIQaKHyNUVdcLiZLeXAt0AOH2iHlNUvJQ3a2WIwFIkeRWYUpd9Hz7gIcDux3nRwKUMtgHckcGqVj1ZiMfDe8U4Ij5Pq0+ko93woz6ZhLu9E+iB87zKey3PZeoC/3j9EnwhtMYvp3+e+IUNF6fOOk36hnhWVGJ0OP299mv5kdTW+UF74eqRsd4iCeYSjVR/Aoh7sG1aZc5csD8CgcafAc8wrl4plWkT8mPRLZxagr/664IFxDYfCW8t/7K3VdcMuWQDdmv6BRcofVzZbf05+1vfj6VDi4Hj4iSDS877yHkUL1lf2FPsvJj6KufqYTl1AkZBndzsx9knnoCsPuPciZEgA7/kAis+pIua7ajqArkfGl/K+0LR2alMw0d5X+4y9JOpUbsf5+C0QbB0MpLIaSxnOKaXdQJy937IRz8S8U1HaX5178UiwLRmjULW2uh4jAfIi39bb5Nfn39501di/94j9kezzFHoj+fZ1rsvDK05x3KQ8qz5afaaEFzjWDHtKzfzD64hCpsDJY4RZyVOrOKfeFKN/moGjHLIlVlSqxKuj6sZSHw5SwxrbWFrJCqFZibZ5kW+bws=
  ALKS_PASSWORD:
    secure: pJLEwcNcv7o4vuww9scWCa9PAr36/UxKqBF0ITQq6p2VFwg94NOwQPjFvs0f5dVjm7Vzo2zQnvDY4YqQsb3jo/kHYxMiZsPclATYfmwDZpmIVgAQKJDt04FvdhnM4BVy6p5sAKOIKwsKeNmq2tCe2eUIi5angfXHkKCoZ7xJH2ywFumAI5AUCmAA4JTm4FBDs353ZLB8CR/IEqIbzFhjPRdkGTzTvNPuouVKVKwwc2YjSn3kbj6IyFuv/QVhXZcRCfu1JE/wDEV35ysK4Mfz8UJ8dBts/2Z2BoCbuUFdJyTncuCyBPxq4SHBZ6GmwkFFeVd+B8d62p+mN3utUp1Cj4ZbN7yo9dkK3IjZqGtvuNeUzfdOA6NqiG51y+sEPy8TYgTo3tYmWbjRs2qPj+55Q50yKtJ5oKCQRMuz25vrAceGSUoeW4op/KB05+7XTN4x0hM6P5/idb1zVh98ip/BriChSAfbpiIlYKMzKrEvvtm+BjllqbVzspDfv1YXwWH06VZyxjz0dYcXBf6FcCjGLRUD8KR7YCUjXnBg6IR+x7IGR0zZDklM5B4yNTZlZMS6OAlyQ3QPM86yBbjxbLGrjKFZh7Eylhu6PA/NCwrM/8bdhXYFR6RnPnC4JhG769pZkFR/+UcWLuaVGKB3iwye94PJ6iyBdF+wejQRoOJv544=
