language: go
sudo: false
go:
- 1.7
- tip
before_install:
- go get github.com/hashicorp/terraform
- go get github.com/hashicorp/go-cleanhttp
install:
- make install
script:
- make test
before_deploy:
- make release
deploy:
  provider: releases
  api_key:
    secure: MZOznxDJeaIT3IQYDZHoH7oazeuM8ekgZzvnUTq0gMHZc1gwB9uEYjvCwSVo0OlUKFPymarhv/65GolggV1+fZzig5HPOpJltTFj3w9RBXZZzZiNZ3X+eexyW+so07BtV1S+jytA/Dd8MpnT9EmCYTzpg6Gp/NosyQJ9FbS7hm8UQcH7PLiBWAeoL1Wb/aLZQZUQRBiYr8PmZ6lzVTY+w8h5KISi7TrL6EzbwXj3j3muCGm/9ZqX/6CAxmAydU0ozCjl4QksRqn2MDWgUSYgga2GKBqsTpU4hX05QCEXD/G2BcGmoaOFP29na+zhXlCZ9j7DrOCMisEWH/DiWwqWaNlqUgO81pGbQDayvpZAMGRrYsaSQTz7oEbuU88NeDFriy44WFGE+eE73ykPFQl6JNnptE3mF6dRVPb6GZhG0nzM+UKfNw4hhcWo45hmrfqLS8MJNci9O3HbMy+2Ka45u64RlX2AUnmNexdPFDmZSjARLrnFT4VUuTEeb3CRS8TmNaWEM1o2yWYgtCkM9qnhiAxlrcDt1Y/bqhgbhzoheslHmi+n9TlFeH1xHP9sTEOwji5ljyPv2iN0/YdInkz+lF/4gEQSZ6hvLGGp+v3FUV66PU8dCusw9ysJhlJ40pvobz7MNdsiscDBx0zqiYUAdSR7XSgUQV7aOJH6dmnqwQA=
  file:
  - release/terraform-provider-alks-darwin-386
  - release/terraform-provider-alks-darwin-amd64
  - release/terraform-provider-alks-freebsd-386
  - release/terraform-provider-alks-freebsd-amd64
  - release/terraform-provider-alks-linux-386
  - release/terraform-provider-alks-linux-amd64
  - release/terraform-provider-alks-solaris-amd64
  - release/terraform-provider-alks-windows-386
  - release/terraform-provider-alks-windows-amd64
  skip_cleanup: true
  on:
    repo: Cox-Automotive/terraform-provider-alks
    tags: true
    all_branches: false
notifications:
  email: false
  slack:
    secure: FbWAAe1dJvSEC5dhIozsPG94it3WusO149EMdp+tq2pP4VqAek1l6yKtfzuns5NJhdQHyYj4ERMd74l5u98vgZWHHHjUMr7d/4eFlAY3OpfyGNjFInqzmsAkccV0z8wB4Os15kOUM4hNYRJPbOm/17xvGi+eWQVj8XxVsowSe7goSazibNyjd4RQCaM0E4u6GDJlAqgKqw4sP07AsXEiWSI/A1KhifoNOXhK7mFIFvEJrhvahlUuHoQ0NrtHSx1IKo+efxip3usmREEmnNERTTUKRhmo0T7drV0j/IWvb1UNkq9MRsNOOyAgAC7hv7D3GXBFTXylzxB68OnU+f79XDGdivaq3qRAu4WukIrB78ygKdeBD/DeFZtB7DoYtGjSKkArjbRCNTSq1Jux68+mxxNmZ5L5vGRO2P7mciuFRfzx3VT6XsAfEpmEj1J834nkOWZa10Bdxfd0AIN9Ay3w7d6i60yp6F+jzCN7IxQSj9xHu3VV+rtgYdh8ablsmN1zGU4EqvXZtz5qUpw66ZCT8Z9xQq5R2aXtzd9v/xtdopMT6madwBrDPyqnwMluWLHO+y7XXJLzP0dd+6eEozs4uldjUgLbI8w+YCaePe1HXQCxxyNAIvOK5OA8uO32VUgK2VgTilZYquQUP1F9ncdNOknwwVMt1SaeBrr7a+k0fbk=
matrix:
  fast_finish: true
  allow_failures:
  - go: tip
env:
  ALKS_URL:
    secure: ZtScKwH8G+uQ4io2jCOc9G38IE29JXaBWk10DibkfcjztS886PZrTezjCl16bYhf3zZ6k9XfF3fQ6T2B636GmUF/d5SbhIPSLaEu5ReFjU2ZggDG9w9hOpZOYv0qDwhaAZ/dLQz4YyoJ9b8quma+OD+883PWszrnJAPA/GIbnBBdd0cOHCAxJBWmKZQpKKli56Oo7KpMfGYdSbvYcnCr74d5l2bRgZzvO6mVjAOS8Uzd9ij345awZU7qhdLklwINYMLZqxgJyXwmLeB27+GSuRqe07LXQVIh07c/d6XrPU4yQ9+TV0v2lPgiXAX3rmsGY3fd2u+P+e/HW4Hg4z3SpTriiac48LgR2O46iNz7SBULCARQNYtCFM1lIAu6+vmCkJMHxfK5YSh4AwQolqs2FpyX+NGAzG0tCiW0fBeZyz8I9hfEDf52z0zVef0FLEEc7kkQIzCTeTLr+dTHPnm3YQ3Xd7YqYNiXT3DKnCwYWmgo2O6OTp0n8qR7acAYKbD55Mtj0GmYNqUYIULB5dlb53PSx8icDGLp7TlxYaPlnyMS8L3M8fvSTXjwA0pj+L9STo6ybrkrk5fSoSzLpq6xFl15I7jc4voCA7ibFV1dXER5vaOuOkHh8chS7kx4DhHTpJqFJYJDgN7f0KhtrEdPbl75dMx7i6KSBfHzuzO+cas=
  ALKS_ACCOUNT:
    secure: U8J2L6bi1RdOapEFvcNEbyqx3g9P0R8g4+06hTC+Uv9RDMiro/7OnWHh+T6bFKDFDA165rFRqnSsiJQsohxVwwv3OSbwA/8+EDdLS8Y3ynGcfTqQO97G8r+14D6k1OBPDE5dV5r2s5Y177ldfDh/ThWPOIXjt2XKFBUYU6I+13Gj3VeAtQcAtx23X9yiEmHmTR/R/z8iqJ7bNYrBpb65CzjirXkdddxKQcuYMYe9By31/psaRZJQG0uq6FTto3uub4YJ2ABCfTge9ZJDlYMwcm0l4Il3bJc7RpAUmWeQc7gSdqHqdxi9qhwFko9+ZTpkt9EsjBPzZF1vOLBU3shaQQ/CYNXzjICmJAjH4ojHHrYsvkjbFz9owIXKoeDd0mZ9Z7MfuVzc5eHQ7g+EnVwss8HrkzjBdEOASOgb3NE7uYWFGR+W5l/ltW1G5SGrHfaOUYj1/AB/DWQxjWlaE4pImLVsoxqCC7yktaaCLfyfEK6wGZNXr7rZYQKxh5uXMzsi02nFnlde1FrkfqnaviNX5AWVY/1MBIbcLrMpXtzp06+Zt+cZuVM4H6l0kHwsXsvQ/3oWtmh2Vppx4tBvTrNj/Gowcj6gxFKQa1YoKpG6u45SVmvIBFPKxxEANA1Dq2HhK8pOHZH/ZD5ghJ0EhU9AGjsk9ZxNGFSj5MyZ957dcag=
  ALKS_ROLE:
    secure: TeTDfrtV6kSo8nMa0JSb6Zl3XLrsNS/MQPhtBAMNw57WIHcDhNHkV0POryjYefXw3DH4a3kXQLxqq5sJLqiV4DBbDo9LLIqFzaPFKtmMiGosC806yEGdHN91t6I30XO1+dKzM/3nLb4Nn/pZDZLF3DAU55iBVDB8mmPq0eZRmap58rG6o+elSG8Z5zeMY391Zq40b3E661YauHYGfr7AJzcY3P3koDeLApIIp0aHJ9nBvHouXZuNU2kJRWRFUHBqOfCZoUiORlDrvunfG5OkcdGmeOc24PfELoPcxBjhaqjnYH7baaIqxJKCl1/vBHfmg3dTBYp4shUQT1eyCmHYVErpy69yQLwvcBuEFccacaiVGDmCzK225tI+/YR3XNKr7RIjWwbWZ7IlZlK4IszuBgJQZ0psWwFew+va8BYmJDJqxnKnSBOQnUrBM4f8VXZwKJM0jZdWbkFjcqKZ+UnGxq2EXUOGoNKCSslcsFyv+gaSnr3EGY28rFA77gBaIiI1tCmwQRIPsHbILXEOqOYqorMi2dGJvJwKkwdYij15YXXA0HW7V/d6g9RKchXiScEykH0DZob2MPGXBmDVFaZu4CQ4Ouz4j3+xDdVfMsNhHAZMiQ5zbTlQ0sUED/8DA1J/caHsmBIQ8k0hId6lCiM2pA6VwuTQXcnYWH2yPuVwGbA=
  ALKS_USERNAME:
    secure: Q9oNCFIJF22cqHJaQpFfwMEGLWE5KgKOip1iq/q8BYZ/y75I4YJ0x/5gcZg/+3WikLDzttSU90Gcbqr2/1AO8YtGrwIiwyvIFPCRD7PSTGIFp80jwH3ByKTi+qKxp+zt8z/PXrLC5JraR9c6nvAuGO0vKosrfnMVl26OONT/S8qzrEXNurIS7r1Wedhar3silF9+U7qT9akVOml0LXUfz7ui6qpgjEn4KkG5/BV+gKDN93NsmsogFsELAhakw0NvXegu4rtaoRc46wkmQFoKhItE+PulFS1SmcPFkWihsflZ3ctFvig87UAeAARNbBtUha0PKMLKtHuLEuBVy4FDVqNbTMTnHM1oDg6aelqVb5p4s+cH8T/45ogyXoBBIyFUq28rqXTJKoUoit5+3XYN4w0GWqhI6D8UQQe0H09pVbe82a5480R7PXEieyuy+ej2LvWdrR8OQtv66kHshk07CM1sQnib2gImiQ5MFGB9w+0UPShbwL2XJe5eLjG/ACiei1mB8UDeWLdPldnig5tFkVdPzzTpnhtl9LwE7qo2bUYdelQH3/I0spo5WDFe16wA0tF8puRv2C1TiHBpCAYxMYd6jcZLhpKzThYMY/C0O/SJi/cXJpOXdCEeCsZcQQddGkdSk746Ah3uawb9QVYa8FGwbZobnkbZ7mblXPFs0t4=
  ALKS_PASSWORD:
    secure: SKZPfSUdgOsoePz4EyJLUWoC4LIbLAMmQPrCUAieHt+cJUEJmVGWAoDqql6ZaWj4IlGTHfFEN8oMeKK9I9eYRlgH/UxV4nO8AqVUabeBrQOo+eVfuz33v2rChJlwRrDaYv8wuMndqmYRokEV33krjApZCbau6C1lOmKwxG+CM04TdWlA/fpPXBIQxhP/Jb132iAKpbo6IH+qJCMJWoM4JMcYGBFN0Al6DWfvK5+rlX2yOE2pxU14Qmm5P8gCsx4Mj8duHxoz2b0vVU+rfHJITTyj8QT4IlYfAaXh4zCPw5DLlxD0CZpQx1r1zr45WWGaBf7wzWShqwIniV+PbdFVy7ArRemIIWnw3XxfpekvW2LFBxb+nKFl7akf5a8y2cTgp2tq8QOF0c8FZA/Yj1Mq1XrwQlSc/nnag+9HHKItrKjhe8bQdS9w+7lBIrUXlDwuaMDIfBoYEVN1kT5m+NeqnpDvWz8Eg3h3wYoMCtzEZnw6GOtRDB4wNdXjHU99jsC0lrpMMV9pEKiNX5oTTgtn49ULHcQUQsmpGUSDiHHLQtZ8r58RGmrDXvca0drS7F2L9xVizH5tJVfzql5qiD28d2/fnsqIyeo/IKY1Ty+96qZ/8oSIWMFaMAaozaU4FBBg21/mx66KXOEhFICPB1zjtUlRr/junHDC6kKdq3qF6dI=
