name: Code Coverage
on:
  pull_request:
    branches:
      - master
    types: [opened, synchronize]

jobs:
  test-coverage:
    name: Upload Coverage to Sonarqube
    runs-on: CAI-Enterprise
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18.x
      - name: generate coverage report
        run: go test -timeout 1200s -v . -coverprofile=./coverage/coverage.out
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}