name: Code Coverage
on:
  pull_request:
    branches:
      - master
    types: [opened, synchronize]

jobs:
  test-coverage:
    name: Upload Coverage to Sonarqube
    runs-on: cai-standard-x86-linux
    steps:
      - name: Checkout repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: Set up Go
        uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5
        with:
          go-version-file: go.mod
      - name: generate coverage report
        run: go test -timeout 1200s -v . -coverprofile=coverage.out
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@713881670b6b3676cda39549040e2d88c70d582e # v8.2.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarqube.coxautoinc.com
        with:
          skipSignatureVerification: true
